port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: :9090
dns:
  enabled: true
  default-nameserver:
    - 119.29.29.29
    - 223.6.6.6
    - 223.5.5.5
  nameserver:
    - 223.6.6.6
    - 223.5.5.5
    - 119.29.29.29
  fallback:
    - https://8.8.8.8/dns-query
    - https://1.1.1.1/dns-query

