[custom]
;去广告：支持
;自动测速：支持
ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,services.googleapis.cn
ruleset=🎯 全球直连,clash-classic:https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt,86400
ruleset=🎯 全球直连,clash-domain:https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt,86400
ruleset=🛑 全球拦截,clash-domain:https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt,86400
ruleset=🎯 全球直连,clash-domain:https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/icloud.txt,86400
ruleset=🎯 全球直连,clash-domain:https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt,86400
ruleset=🚀 节点选择,clash-domain:https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/google.txt,86400
ruleset=🚀 节点选择,clash-domain:https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt,86400
ruleset=🎯 全球直连,clash-domain:https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt,86400
ruleset=🎯 全球直连,[]GEOSITE,cn
ruleset=🚀 节点选择,[]GEOSITE,geolocation-!cn
ruleset=🎯 全球直连,[]GEOIP,LAN,no-resolve
ruleset=🎯 全球直连,[]GEOIP,CN,no-resolve
ruleset=🐟 漏网之鱼,[]FINAL

;custom_proxy_group=🚀 节点选择`select`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇰🇷 韩国节点`[]🇯🇵 日本节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]☑️ 手动切换
custom_proxy_group=🚀 节点选择`select`[]🇰🇷 韩国节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]☑️ 手动切换
custom_proxy_group=☑️ 手动切换`select`.*
;custom_proxy_group=🇺🇲 美国节点`url-test`(美|US|United States)`http://www.gstatic.com/generate_204`210,,10
custom_proxy_group=🇭🇰 香港节点`url-test`(港|HK|hk|Hong Kong|HongKong|hongkong)`http://www.gstatic.com/generate_204`210,,10
custom_proxy_group=🇰🇷 韩国节点`url-test`(KR|Korea|KOR|首尔|韩|韓)`http://www.gstatic.com/generate_204`210,,10
custom_proxy_group=🇯🇵 日本节点`url-test`(日本|[^-]日|JP|Japan)`http://www.gstatic.com/generate_204`210,,10
custom_proxy_group=🇹🇼 台湾节点`url-test`(台|TW|Taiwan)`http://www.gstatic.com/generate_204`210,,10
custom_proxy_group=🇸🇬 狮城节点`url-test`(新加坡|坡|狮城|SG|Singapore)`http://www.gstatic.com/generate_204`210,,10
custom_proxy_group=🎯 全球直连`select`[]DIRECT
custom_proxy_group=🛑 全球拦截`select`[]REJECT
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择
enable_rule_generator=true
overwrite_original_rules=true
clash_rule_base=https://raw.githubusercontent.com/freesh2023/Clash_Subconfig/main/base.yaml
